dist: bionic
os: linux
language: cpp
env:
    global:
        - CC=gcc-8
        - CXX=g++-8
        - DEVKITPRO=$HOME
        - DEVKITPPC=$DEVKITPRO/devkitPPC

addons:
    apt:
        packages:
            - g++-8-multilib
            - linux-libc-dev
            - wine32
            - wine-stable

cache:
    apt: true

install:
    - mkdir -p $HOME/download
    - pushd $HOME/download
    - travis_retry wget https://cdn.discordapp.com/attachments/751089877579202691/751090418636029972/GC_COMPILERS.zip
    - travis_retry wget https://www.red031000.com/pbr/baserom.dol
    - travis_retry wget https://github.com/devkitPro/buildscripts/releases/download/devkitPPC_r35/devkitPPC_r35-linux.tar.xz
    - travis_retry wget https://www.red031000.com/pbr/powerpc-eabi-objcopy
    - tar xJf devkitPPC*.tar.xz -C $HOME
    - sudo chmod 775 powerpc-eabi-objcopy
    - mv -f powerpc-eabi-objcopy $DEVKITPPC/bin/powerpc-eabi-objcopy
    - $DEVKITPPC/bin/powerpc-eabi-objcopy --version
    - mkdir $TRAVIS_BUILD_DIR/tools/mwcc_compiler
    - unzip GC_COMPILERS.zip -d $TRAVIS_BUILD_DIR/tools/mwcc_compiler
    - mv baserom.dol $TRAVIS_BUILD_DIR
    - popd

script:
    - travis_retry make

notifications:
    email: false
